/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 25-Feb.-2026 10:35:37 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallerecursomant_Mantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallerecursomant] DROP CONSTRAINT [FK_Detallerecursomant_Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallerecursomant_Recurso]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallerecursomant] DROP CONSTRAINT [FK_Detallerecursomant_Recurso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Diadisponible_Tecnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Diadisponible] DROP CONSTRAINT [FK_Diadisponible_Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Area]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Tipoequipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Tipoequipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Estadoequipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Estadoequipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Estadomantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Estadomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Tecnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Planmantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Planmantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Tipomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Estadoplanmant]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Estadoplanmant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Frecuencia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Frecuencia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Planmantenimiento_Prioridad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Planmantenimiento] DROP CONSTRAINT [FK_Planmantenimiento_Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tecnico_Ciudad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tecnico] DROP CONSTRAINT [FK_Tecnico_Ciudad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tecnico_Estadotécnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tecnico] DROP CONSTRAINT [FK_Tecnico_Estadotécnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tecnico_Rubro]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tecnico] DROP CONSTRAINT [FK_Tecnico_Rubro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Area]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ciudad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ciudad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Detallerecursomant]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Detallerecursomant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Diadisponible]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Diadisponible]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Equipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estadoequipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estadoequipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estadomantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estadomantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estadoplanmant]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estadoplanmant]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estadotécnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estadotécnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Frecuencia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Frecuencia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Mantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Planmantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Planmantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prioridad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Recurso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Recurso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rubro]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rubro]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tecnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipoequipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipoequipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipomantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipomantenimiento]
GO

/* Create Tables */

CREATE TABLE [Area]
(
	[AreaID] int NOT NULL IDENTITY (1, 1),
	[NombreArea] varchar(50) NOT NULL
)
GO

CREATE TABLE [Ciudad]
(
	[CiudadID] int NOT NULL IDENTITY (1, 1),
	[CiudadNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Detallerecursomant]
(
	[DetallerecursomantID] int NOT NULL IDENTITY (1, 1),
	[MantenimientoID] int NOT NULL,
	[CatidadUsada] int NOT NULL,
	[RecursoID] int NOT NULL
)
GO

CREATE TABLE [Diadisponible]
(
	[DiadisponibleID] int NOT NULL IDENTITY (1, 1),
	[DiaSemana] varchar(50) NOT NULL,
	[TecnicoID] int NOT NULL
)
GO

CREATE TABLE [Equipo]
(
	[EquipoID] int NOT NULL IDENTITY (1, 1),
	[AreaID] int NOT NULL,
	[TipoequipoID] int NOT NULL,
	[EstadoequipoID] int NOT NULL,
	[NombreEquipo] varchar(50) NOT NULL,
	[FechaRegistroEquipo] datetime NOT NULL
)
GO

CREATE TABLE [Estadoequipo]
(
	[EstadoequipoID] int NOT NULL IDENTITY (1, 1),
	[EstadoEquipoNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Estadomantenimiento]
(
	[EstadomantenimientoID] int NOT NULL IDENTITY (1, 1),
	[EstadoMantNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Estadoplanmant]
(
	[EstadoplanmantID] int NOT NULL IDENTITY (1, 1),
	[EstadoPlanMantNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Estadotécnico]
(
	[EstadotécnicoID] int NOT NULL IDENTITY (1, 1),
	[EstadoTecniconNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Frecuencia]
(
	[FrecuenciaID] int NOT NULL IDENTITY (1, 1),
	[FrecuenciaNomb] varchar(50) NOT NULL
)
GO

CREATE TABLE [Mantenimiento]
(
	[MantenimientoID] int NOT NULL IDENTITY (1, 1),
	[EquipoID] int NOT NULL,
	[EstadomantenimientoID] int NOT NULL,
	[TecnicoID] int NOT NULL,
	[PlanmantenimientoID] int NULL,
	[FechaRealizacion] varchar(50) NOT NULL,
	[TipomantenimientoID] int NOT NULL,
	[DescripciónMantenimiento] varchar(100) NOT NULL
)
GO

CREATE TABLE [Planmantenimiento]
(
	[PlanmantenimientoID] int NOT NULL IDENTITY (1, 1),
	[EquipoID] int NOT NULL,
	[EstadoplanmantID] int NOT NULL,
	[FrecuenciaID] int NOT NULL,
	[FechaInicioPlan] datetime NOT NULL,
	[PrioridadID] int NOT NULL,
	[DescripcionPlan] varchar(100) NOT NULL
)
GO

CREATE TABLE [Prioridad]
(
	[PrioridadID] int NOT NULL IDENTITY (1, 1),
	[PrioridadPlanNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Recurso]
(
	[NombreRecurso] varchar(50) NOT NULL,
	[RecursoID] int NOT NULL IDENTITY (1, 1),
	[StockRecurso] int NOT NULL
)
GO

CREATE TABLE [Rubro]
(
	[RubroID] int NOT NULL IDENTITY (1, 1),
	[RubroNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Tecnico]
(
	[TecnicoID] int NOT NULL IDENTITY (1, 1),
	[CiudadID] int NOT NULL,
	[EstadotécnicoID] int NOT NULL,
	[NombreTecnico] varchar(50) NOT NULL,
	[RubroID] int NOT NULL,
	[DNITécnico] int NOT NULL,
	[CorreoTecnico] varchar(7) NOT NULL,
	[TelefonoTecnico] varchar(9) NOT NULL
)
GO

CREATE TABLE [Tipoequipo]
(
	[TipoequipoID] int NOT NULL IDENTITY (1, 1),
	[TipoEquipoNom] varchar(50) NOT NULL
)
GO

CREATE TABLE [Tipomantenimiento]
(
	[TipomantenimientoID] int NOT NULL IDENTITY (1, 1),
	[TipoMantenimientoNom] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Area] 
 ADD CONSTRAINT [PK_Area]
	PRIMARY KEY CLUSTERED ([AreaID] ASC)
GO

ALTER TABLE [Ciudad] 
 ADD CONSTRAINT [PK_Ciudad]
	PRIMARY KEY CLUSTERED ([CiudadID] ASC)
GO

ALTER TABLE [Detallerecursomant] 
 ADD CONSTRAINT [PK_Detallerecursomant]
	PRIMARY KEY CLUSTERED ([DetallerecursomantID] ASC)
GO

ALTER TABLE [Diadisponible] 
 ADD CONSTRAINT [PK_Diadisponible]
	PRIMARY KEY CLUSTERED ([DiadisponibleID] ASC)
GO

ALTER TABLE [Equipo] 
 ADD CONSTRAINT [PK_Equipo]
	PRIMARY KEY CLUSTERED ([EquipoID] ASC)
GO

ALTER TABLE [Estadoequipo] 
 ADD CONSTRAINT [PK_Estadoequipo]
	PRIMARY KEY CLUSTERED ([EstadoequipoID] ASC)
GO

ALTER TABLE [Estadomantenimiento] 
 ADD CONSTRAINT [PK_Estadomantenimiento]
	PRIMARY KEY CLUSTERED ([EstadomantenimientoID] ASC)
GO

ALTER TABLE [Estadoplanmant] 
 ADD CONSTRAINT [PK_Estadoplanmant]
	PRIMARY KEY CLUSTERED ([EstadoplanmantID] ASC)
GO

ALTER TABLE [Estadotécnico] 
 ADD CONSTRAINT [PK_Estadotécnico]
	PRIMARY KEY CLUSTERED ([EstadotécnicoID] ASC)
GO

ALTER TABLE [Frecuencia] 
 ADD CONSTRAINT [PK_Frecuencia]
	PRIMARY KEY CLUSTERED ([FrecuenciaID] ASC)
GO

ALTER TABLE [Mantenimiento] 
 ADD CONSTRAINT [PK_Mantenimiento]
	PRIMARY KEY CLUSTERED ([MantenimientoID] ASC)
GO

ALTER TABLE [Planmantenimiento] 
 ADD CONSTRAINT [PK_Planmantenimiento]
	PRIMARY KEY CLUSTERED ([PlanmantenimientoID] ASC)
GO

ALTER TABLE [Prioridad] 
 ADD CONSTRAINT [PK_Prioridad]
	PRIMARY KEY CLUSTERED ([PrioridadID] ASC)
GO

ALTER TABLE [Recurso] 
 ADD CONSTRAINT [PK_Recurso]
	PRIMARY KEY CLUSTERED ([RecursoID] ASC)
GO

ALTER TABLE [Rubro] 
 ADD CONSTRAINT [PK_Rubro]
	PRIMARY KEY CLUSTERED ([RubroID] ASC)
GO

ALTER TABLE [Tecnico] 
 ADD CONSTRAINT [PK_Tecnico]
	PRIMARY KEY CLUSTERED ([TecnicoID] ASC)
GO

ALTER TABLE [Tipoequipo] 
 ADD CONSTRAINT [PK_Tipoequipo]
	PRIMARY KEY CLUSTERED ([TipoequipoID] ASC)
GO

ALTER TABLE [Tipomantenimiento] 
 ADD CONSTRAINT [PK_Tipomantenimiento]
	PRIMARY KEY CLUSTERED ([TipomantenimientoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Detallerecursomant] ADD CONSTRAINT [FK_Detallerecursomant_Mantenimiento]
	FOREIGN KEY ([MantenimientoID]) REFERENCES [Mantenimiento] ([MantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallerecursomant] ADD CONSTRAINT [FK_Detallerecursomant_Recurso]
	FOREIGN KEY ([RecursoID]) REFERENCES [Recurso] ([RecursoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Diadisponible] ADD CONSTRAINT [FK_Diadisponible_Tecnico]
	FOREIGN KEY ([TecnicoID]) REFERENCES [Tecnico] ([TecnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Area]
	FOREIGN KEY ([AreaID]) REFERENCES [Area] ([AreaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Tipoequipo]
	FOREIGN KEY ([TipoequipoID]) REFERENCES [Tipoequipo] ([TipoequipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Estadoequipo]
	FOREIGN KEY ([EstadoequipoID]) REFERENCES [Estadoequipo] ([EstadoequipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Equipo]
	FOREIGN KEY ([EquipoID]) REFERENCES [Equipo] ([EquipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Estadomantenimiento]
	FOREIGN KEY ([EstadomantenimientoID]) REFERENCES [Estadomantenimiento] ([EstadomantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Tecnico]
	FOREIGN KEY ([TecnicoID]) REFERENCES [Tecnico] ([TecnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Planmantenimiento]
	FOREIGN KEY ([PlanmantenimientoID]) REFERENCES [Planmantenimiento] ([PlanmantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Tipomantenimiento]
	FOREIGN KEY ([TipomantenimientoID]) REFERENCES [Tipomantenimiento] ([TipomantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Equipo]
	FOREIGN KEY ([EquipoID]) REFERENCES [Equipo] ([EquipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Estadoplanmant]
	FOREIGN KEY ([EstadoplanmantID]) REFERENCES [Estadoplanmant] ([EstadoplanmantID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Frecuencia]
	FOREIGN KEY ([FrecuenciaID]) REFERENCES [Frecuencia] ([FrecuenciaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Planmantenimiento] ADD CONSTRAINT [FK_Planmantenimiento_Prioridad]
	FOREIGN KEY ([PrioridadID]) REFERENCES [Prioridad] ([PrioridadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tecnico] ADD CONSTRAINT [FK_Tecnico_Ciudad]
	FOREIGN KEY ([CiudadID]) REFERENCES [Ciudad] ([CiudadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tecnico] ADD CONSTRAINT [FK_Tecnico_Estadotécnico]
	FOREIGN KEY ([EstadotécnicoID]) REFERENCES [Estadotécnico] ([EstadotécnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tecnico] ADD CONSTRAINT [FK_Tecnico_Rubro]
	FOREIGN KEY ([RubroID]) REFERENCES [Rubro] ([RubroID]) ON DELETE No Action ON UPDATE No Action
GO

INSERT INTO Area (NombreArea) VALUES
('Emergencia'),
('Unidad de Cuidados Intensivos'),
('Centro Quirúrgico'),
('Hospitalización'),
('Laboratorio Clínico'),
('Imagenología'),
('Rayos X'),
('Tomografía'),
('Resonancia Magnética'),
('Ecografía'),
('Banco de Sangre'),
('Hemodiálisis'),
('Neonatología'),
('Central de Esterilización'),
('Farmacia'),
('Fisioterapia y Rehabilitación');

INSERT INTO EstadoEquipo (EstadoEquipoNom) VALUES
('Operativo'),
('Fuera de servicio'),
('Dado de baja');

INSERT INTO TipoEquipo (TipoEquipoNom) VALUES
('Mecánico'),
('Eléctrico'),
('Electrónico'),
('Electromecánico'),
('Biomédico'),
('Refrigeración'),
('Climatización'),
('Hidráulico'),
('Neumático'),
('Informático');

INSERT INTO Rubro (RubroNom) VALUES
('Mecánico'),
('Eléctrico'),
('Electrónico'),
('Electromecánico'),
('Biomédico'),
('Refrigeración'),
('Climatización'),
('Hidráulico'),
('Neumático'),
('Informático');

INSERT INTO Ciudad (CiudadNom) VALUES
('Lima'),
('Arequipa'),
('Trujillo'),
('Chiclayo'),
('Piura'),
('Tumbes'),
('Cajamarca'),
('Chachapoyas'),
('Huaraz'),
('Huánuco'),
('Iquitos'),
('Pucallpa'),
('Tarapoto'),
('Moyobamba'),
('Cusco'),
('Puno'),
('Juliaca'),
('Ayacucho'),
('Huancavelica'),
('Huancayo'),
('Cerro de Pasco'),
('Tacna'),
('Moquegua'),
('Puerto Maldonado'),
('Abancay');
select * from Estadotécnico
INSERT INTO  Estadoplanmant(EstadoPlanMantNom) VALUES
('Activo'),
('Inhabilitado'),
('Completo');

INSERT INTO  Estadomantenimiento(EstadoMantNom) VALUES
('Pendiente'),
('En curso'),
('Completo');

INSERT INTO  Estadotécnico(EstadoTecniconNom) VALUES
('Habilitado'),
('Inhabilitado'),
('Dado de baja');

INSERT INTO  Frecuencia(FrecuenciaNomb) VALUES
('Diario'),
('Semanal'),
('Mensual'),
('Trimestral'),
('Anual');

INSERT INTO  Prioridad(PrioridadPlanNom) VALUES
('Baja'),
('Media'),
('Alta');

INSERT INTO  Tipomantenimiento(TipoMantenimientoNom) VALUES
('Correctivo'),
('Predictivo'),
('Emergencia');

INSERT INTO Recurso (NombreRecurso, StockRecurso) VALUES
('Aceite lubricante', 50),
('Filtro de aire', 30),
('Filtro de agua', 25),
('Correa industrial', 20),
('Fusible', 100),
('Cable eléctrico', 200),
('Interruptor', 40),
('Sensor de temperatura', 15),
('Sensor de presión', 10),
('Válvula', 12),
('Sello mecánico', 18),
('Rodamiento', 35),
('Grasa industrial', 45),
('Alcohol isopropílico', 60),
('Solución desinfectante', 80),
('Lubricante en aerosol', 25),
('Cinta aislante', 70),
('Terminal eléctrico', 120),
('Tornillo', 500),
('Tuerca', 500),
('Arandela', 500),
('Electrodos', 40),
('Manguera médica', 30),
('Conector médico', 25),
('Batería recargable', 20),
('Fuente de poder', 10),
('Placa electrónica', 8);

INSERT INTO Tecnico
(CiudadID, EstadotécnicoID, NombreTecnico, RubroID, DNITécnico, CorreoTecnico, TelefonoTecnico)
VALUES
(1, 1, 'Juan Pérez',        4, 71234567, 'juan.perez@hospital.pe', '987654321'),
(1, 1, 'María López',       5, 72345678, 'maria.lopez@hospital.pe', '987654322'),
(2, 1, 'Carlos Ramírez',    1, 73456789, 'carlos.ramirez@hospital.pe', '987654323'),
(2, 1, 'Ana Torres',        2, 74567890, 'ana.torres@hospital.pe', '987654324'),
(3, 1, 'Luis Fernández',    3, 75678901, 'luis.fernandez@hospital.pe', '987654325'),
(3, 2, 'Pedro Castillo',    1, 76789012, 'pedro.castillo@hospital.pe', '987654326'),
(1, 1, 'Rosa Martínez',     2, 77890123, 'rosa.martinez@hospital.pe', '987654327'),
(2, 1, 'Jorge Salazar',     4, 78901234, 'jorge.salazar@hospital.pe', '987654328');

INSERT INTO DiaDisponible
(DiaSemana, TecnicoID)
VALUES
-- Técnico 1
('Lunes', 1),
('Miércoles', 1),
('Viernes', 1),

-- Técnico 2
('Martes', 2),
('Jueves', 2),

-- Técnico 3
('Lunes', 3),
('Martes', 3),
('Miércoles', 3),
('Jueves', 3),
('Viernes', 3),

-- Técnico 4
('Sábado', 4),

-- Técnico 5
('Lunes', 5),
('Miércoles', 5);

select * from Tecnico
INSERT INTO Equipo
(AreaID, TipoequipoID, EstadoequipoID, Nombreequipo, FechaRegistroEquipo)
VALUES
-- Emergencia
(1, 5, 1, 'Monitor multiparámetro Emergencia', '2025-10-10 08:00:00'),
(1, 4, 1, 'Camilla hidráulica Emergencia',     '2025-10-12 09:00:00'),

-- UCI
(2, 5, 1, 'Ventilador mecánico UCI',            '2025-11-01 10:00:00'),
(2, 5, 2, 'Bomba de infusión UCI',              '2025-11-05 11:00:00'),

-- Centro Quirúrgico
(3, 4, 1, 'Mesa quirúrgica eléctrica',          '2025-09-20 08:30:00'),
(3, 3, 1, 'Lámpara quirúrgica LED',              '2025-09-22 09:15:00'),

-- Laboratorio
(4, 3, 1, 'Centrífuga de laboratorio',           '2025-10-18 10:45:00'),
(4, 3, 3, 'Analizador hematológico',             '2025-10-20 14:00:00'),

-- Imagenología
(5, 3, 1, 'Equipo de Rayos X',                    '2025-08-15 08:00:00'),
(5, 3, 1, 'Ecógrafo digital',                    '2025-08-18 09:30:00');

INSERT INTO Planmantenimiento
(EquipoID, EstadoplanmantID, FrecuenciaID, FechainicioPlan, PrioridadID, DescripcionPlan)
VALUES
-- Plan mensual: inspección y limpieza general
(1, 1, 1, '2026-01-01 08:00:00', 1,
 'Inspección general del equipo, limpieza de componentes, verificación de funcionamiento y ajustes menores'),

-- Plan trimestral: revisión mecánica
(2, 1, 2, '2026-01-15 08:00:00', 2,
 'Revisión mecánica completa, lubricación de partes móviles y detección de desgaste'),

-- Plan semestral: mantenimiento profundo
(3, 1, 3, '2026-02-01 08:00:00', 3,
 'Mantenimiento preventivo profundo, cambio de piezas de desgaste y pruebas de rendimiento'),

-- Plan completado: mantenimiento preventivo
(4, 2, 1, '2025-10-01 08:00:00', 1,
 'Mantenimiento preventivo programado con inspección, limpieza y calibración del equipo'),

-- Plan mensual adicional
(5, 1, 1, '2026-02-10 08:00:00', 2,
 'Inspección periódica del equipo, ajuste de parámetros operativos y limpieza básica');

INSERT INTO Mantenimiento
(EquipoID, EstadoMantenimientoID, TecnicoID, PlanmantenimientoID, FechaRealizacion, TipoMantenimientoID, DescripciónMantenimiento)
VALUES
-- Predictivo pendiente (con plan)
(1, 1, 1, 1, '2026-02-24 09:00:00', 1,
 'Inspección predictiva programada del equipo'),

-- Correctivo en proceso (sin plan)
(2, 2, 2, NULL, '2026-02-24 11:30:00', 2,
 'Corrección de falla detectada durante la operación'),

-- Emergencia completada (sin plan)
(1, 3, 3, NULL, '2026-02-23 18:45:00', 3,
 'Atención de emergencia por detención inesperada del equipo'),

-- Predictivo completado (con plan)
(1, 3, 4, 2, '2026-02-20 08:00:00', 1,
 'Ejecución de mantenimiento predictivo según plan');

 INSERT INTO DetalleRecursoMant
(MantenimientoID, CatidadUsada ,  RecursoID)
VALUES
-- Recursos usados en mantenimiento 1
(1, 2, 1),   -- Aceite lubricante
(1, 4, 5),   -- Fusibles

-- Recursos usados en mantenimiento 2
(2, 1, 2),   -- Filtro de aire
(2, 10, 6),  -- Cable eléctrico

-- Recursos usados en mantenimiento 3
(3, 2, 3),   -- Correa industrial
(3, 1, 12),  -- Rodamiento

-- Recursos usados en mantenimiento 4
(4, 1, 1),   -- Aceite lubricante
(4, 2, 7);   -- Interruptor

select * from Detallerecursomant