/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-Feb.-2026 01:53:29 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */


IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Equipo_Area]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Equipo] DROP CONSTRAINT [FK_Equipo_Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Equipo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Estado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Prioridad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_TipoMantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_TipoMantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Mantenimiento_Tecnico]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Mantenimiento] DROP CONSTRAINT [FK_Mantenimiento_Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Recurso_Mantenimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Recurso] DROP CONSTRAINT [FK_Recurso_Mantenimiento]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Area]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Area]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Equipo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Equipo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Mantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Mantenimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prioridad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prioridad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Recurso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Recurso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tecnico]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tecnico]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TipoMantenimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TipoMantenimiento]
GO

/* Create Tables */

CREATE TABLE [Area]
(
	[AreaID] int NOT NULL
)
GO

CREATE TABLE [Equipo]
(
	[EquipoID] int NOT NULL,
	[AreaID] int NULL
)
GO

CREATE TABLE [Estado]
(
	[EstadoID] int NOT NULL
)
GO

CREATE TABLE [Mantenimiento]
(
	[MantenimientoID] int NULL,
	[EquipoID] int NULL,
	[EstadoID] int NOT NULL,
	[PrioridadID] int NOT NULL,
	[TipoMantenimientoID] int NOT NULL,
	[TecnicoID] int NULL
)
GO

CREATE TABLE [Prioridad]
(
	[PrioridadID] int NOT NULL
)
GO

CREATE TABLE [Recurso]
(
	[RecursoID] int NOT NULL,
	[MantenimientoID] int NOT NULL
)
GO

CREATE TABLE [Tecnico]
(
	[TecnicoID] int NOT NULL
)
GO

CREATE TABLE [TipoMantenimiento]
(
	[TipoMantenimientoID] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Area] 
 ADD CONSTRAINT [PK_Area]
	PRIMARY KEY CLUSTERED ([AreaID] ASC)
GO

ALTER TABLE [Equipo] 
 ADD CONSTRAINT [PK_Equipo]
	PRIMARY KEY CLUSTERED ([EquipoID] ASC)
GO

ALTER TABLE [Estado] 
 ADD CONSTRAINT [PK_Estado]
	PRIMARY KEY CLUSTERED ([EstadoID] ASC)
GO

ALTER TABLE [Mantenimiento] 
 ADD CONSTRAINT [PK_Mantenimiento]
	PRIMARY KEY CLUSTERED ([MantenimientoID] ASC)
GO

ALTER TABLE [Prioridad] 
 ADD CONSTRAINT [PK_Prioridad]
	PRIMARY KEY CLUSTERED ([PrioridadID] ASC)
GO

ALTER TABLE [Recurso] 
 ADD CONSTRAINT [PK_Recurso]
	PRIMARY KEY CLUSTERED ([RecursoID] ASC)
GO

ALTER TABLE [Tecnico] 
 ADD CONSTRAINT [PK_Tecnico]
	PRIMARY KEY CLUSTERED ([TecnicoID] ASC)
GO

ALTER TABLE [TipoMantenimiento] 
 ADD CONSTRAINT [PK_TipoMantenimiento]
	PRIMARY KEY CLUSTERED ([TipoMantenimientoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Equipo] ADD CONSTRAINT [FK_Equipo_Area]
	FOREIGN KEY ([AreaID]) REFERENCES [Area] ([AreaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Equipo]
	FOREIGN KEY ([EquipoID]) REFERENCES [Equipo] ([EquipoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Estado]
	FOREIGN KEY ([EstadoID]) REFERENCES [Estado] ([EstadoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Prioridad]
	FOREIGN KEY ([PrioridadID]) REFERENCES [Prioridad] ([PrioridadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_TipoMantenimiento]
	FOREIGN KEY ([TipoMantenimientoID]) REFERENCES [TipoMantenimiento] ([TipoMantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Mantenimiento] ADD CONSTRAINT [FK_Mantenimiento_Tecnico]
	FOREIGN KEY ([TecnicoID]) REFERENCES [Tecnico] ([TecnicoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Recurso] ADD CONSTRAINT [FK_Recurso_Mantenimiento]
	FOREIGN KEY ([MantenimientoID]) REFERENCES [Mantenimiento] ([MantenimientoID]) ON DELETE No Action ON UPDATE No Action
GO

CREATE PROCEDURE [dbo].[spInsertaMantenimiento] 
(
	@EquipoID integer,
	@EstadoID integer,
	@PrioridadID integer,
	@TipoMantenimientoID integer,
	@TecnicoID integer
)
AS
BEGIN
    INSERT INTO Mantenimiento(EquipoID,EstadoID,PrioridadID,TipoMantenimientoID,TecnicoID) 
    VALUES ( 
	@EquipoID,@EstadoID,@PrioridadID,@TipoMantenimientoID,@TecnicoID)
END
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spListaMantenimiento]
as  
begin
   select * from Mantenimiento
end
GO
USE [master]
GO
ALTER DATABASE [MANTENIMIENTODB] SET  READ_WRITE 
GO
